### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by MrSunny** [scottgonzalez/node-git-tools#7]
there is an error i don`t understand , can u help me ?

    var repo = new Repo( "gitpath" );
    repo.authors(function( error, authors ) {
	    console.log( error,authors );
    });

	{ [Error: spawn git ENOENT]
	  code: 'ENOENT',
	  errno: 'ENOENT',
	  syscall: 'spawn git',
	  path: 'git' }

**Comment by scottgonzalez** [comment]
`ENOENT` means that `"gitpath"` does not exist.

**Comment by scottgonzalez** [comment]
The error is just a direct pass-through from the process spawning. I'd be happy to customize the error message if that would help.
