### ISSUE TITLE
Error in blame?

### ISSUE THREAD

**Issue by yamikuronue** [scottgonzalez/node-git-tools#9]
I'm getting 
```
                        var commit = matches[ 1 ];
                                            ^
TypeError: Cannot read property '1' of null
```
sometimes when I try to run Blame. I'm not at all certain why, and I can't trap the error to recover from it. 
The relevant lines seem to be:
```
var rBlame = /^(\^?\w+)(\s(\S+))?\s+(\d+)\)\s(.*)$/;
lines = lines.map(function( line ) {
var matches = rBlame.exec( line );
var commit = matches[ 1 ];
```

Any idea what's going on? Could there be some better error handling here?

**Comment by scottgonzalez** [comment]
The error should happen consistently given a specific path and SHA. Does this happen on a public repo that I can test against?

**Comment by yamikuronue** [comment]
Yes :) You can see what I'm working on here: https://github.com/yamikuronue/BusFactor .For testing I'm running it against its own repo, so that's also the repository I'm working against.

After some time spent trying to narrow down which paths it was choking on, it's the README and LICENSE that I let Github automatically generate to start the repo. Could there be something weird with that initial commit?https://github.com/yamikuronue/BusFactor/commit/91f49a05b5175f43963e7e809bf25a1f0ff85779

**Comment by scottgonzalez** [comment]
Fixed and released as v0.2.0.

**Comment by yamikuronue** [comment]
I'm still getting the same problem using v0.2.0....

```
> npm install
async@1.3.0 node_modules\async

git-tools@0.2.0 node_modules\git-tools
└── spawnback@1.0.0
```
```
> node .\index.js
node_modules\git-tools\git-tools.js:24
                        email: matches[ 1 ],
                                      ^
TypeError: Cannot read property '1' of null
```

**Comment by scottgonzalez** [comment]
Can you provide the exact command you're running?

**Comment by scottgonzalez** [comment]
Blames don't run the code you just pointed to. It's entirely possible that I broke a different method while fixing this, though. I'm going to re-close this, but please do file a new issue with some more details about what's broken now. I'll try to flesh out the test suite a bit, but this isn't the easiest module to test.
